// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG5QaoMxq4eHtKO3wSRLnjPXdHujAV8Ow',
    appId: '1:114440682314:web:85c4e204bfaa3a3534dfb3',
    messagingSenderId: '114440682314',
    projectId: 'fir-comp3310',
    authDomain: 'fir-comp3310.firebaseapp.com',
    storageBucket: 'fir-comp3310.appspot.com',
    measurementId: 'G-DMPX1YL4DW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXcZpAyo2H78EkoPkI7YARNNZBMEa-kjg',
    appId: '1:114440682314:android:d5e9872c4445f82634dfb3',
    messagingSenderId: '114440682314',
    projectId: 'fir-comp3310',
    storageBucket: 'fir-comp3310.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChpcUKdurykkIiGd0MJ4PaKyIGCt4dkvs',
    appId: '1:114440682314:ios:4aae933c86f1f7e534dfb3',
    messagingSenderId: '114440682314',
    projectId: 'fir-comp3310',
    storageBucket: 'fir-comp3310.appspot.com',
    iosBundleId: 'com.example.project1MobdevJack917596040',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChpcUKdurykkIiGd0MJ4PaKyIGCt4dkvs',
    appId: '1:114440682314:ios:4aae933c86f1f7e534dfb3',
    messagingSenderId: '114440682314',
    projectId: 'fir-comp3310',
    storageBucket: 'fir-comp3310.appspot.com',
    iosBundleId: 'com.example.project1MobdevJack917596040',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDG5QaoMxq4eHtKO3wSRLnjPXdHujAV8Ow',
    appId: '1:114440682314:web:4f357349b956f4fe34dfb3',
    messagingSenderId: '114440682314',
    projectId: 'fir-comp3310',
    authDomain: 'fir-comp3310.firebaseapp.com',
    storageBucket: 'fir-comp3310.appspot.com',
    measurementId: 'G-3X6F6D9CZ4',
  );
}
